import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";

const geist = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const BASE_URL = "https://geo.goushaoai.com";

const TITLE       = "GS GEO | AI 搜索可见度优化专家";
const DESCRIPTION =
  "GS GEO 帮助企业提升在 ChatGPT、Claude、Perplexity、豆包、DeepSeek 等 AI 搜索结果中的品牌曝光。提供 GEO 搜索体检、品牌 AI 可见度分析、AI 引用优化、持续运营一站式服务。";
const KEYWORDS = [
  "GS GEO", "GEO 优化", "AI SEO", "AI 可见度", "AI 搜索优化",
  "LLMO", "AEO", "生成式引擎优化", "品牌 AI 曝光",
  "ChatGPT 优化", "Claude 引用", "Perplexity 排名",
  "豆包 SEO", "DeepSeek 曝光", "AI 搜索营销",
];

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),

  title: {
    default: TITLE,
    template: "%s | GS GEO",
  },
  description: DESCRIPTION,
  keywords: KEYWORDS,
  authors: [{ name: "GS GEO", url: BASE_URL }],
  creator: "GS GEO",
  publisher: "GS GEO",

  /* ── Canonical URL ─────────────────────────── */
  alternates: {
    canonical: BASE_URL,
    languages: { "zh-CN": BASE_URL },
  },

  /* ── Favicon / Icons ───────────────────────── */
  icons: {
    icon: [
      { url: "/gs-logo.png", type: "image/png" },
    ],
    apple: "/gs-logo.png",
    shortcut: "/gs-logo.png",
  },

  /* ── Open Graph ────────────────────────────── */
  openGraph: {
    type: "website",
    locale: "zh_CN",
    url: BASE_URL,
    siteName: "GS GEO",
    title: TITLE,
    description: DESCRIPTION,
    images: [
      {
        url: "/opengraph-image",   // auto-generated by app/opengraph-image.tsx
        width: 1200,
        height: 630,
        alt: "GS GEO — AI 搜索可见度优化专家",
      },
    ],
  },

  /* ── Twitter / X Card ──────────────────────── */
  twitter: {
    card: "summary_large_image",
    site: "@GSGEO",
    creator: "@GSGEO",
    title: TITLE,
    description: DESCRIPTION,
    images: ["/opengraph-image"],
  },

  /* ── Robots ────────────────────────────────── */
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  /* ── Verification (fill in after submitting to Search Console) ── */
  // verification: {
  //   google: "YOUR_GOOGLE_VERIFICATION_TOKEN",
  //   other: { "baidu-site-verification": "YOUR_BAIDU_TOKEN" },
  // },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="zh-CN" className={`${geist.variable} scroll-smooth`}>
      <head>
        {/* Structured data — Organization */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: "GS GEO",
              alternateName: "GS GEO AI 搜索可见度优化",
              url: BASE_URL,
              logo: `${BASE_URL}/gs-logo.png`,
              description: DESCRIPTION,
              contactPoint: {
                "@type": "ContactPoint",
                telephone: "+86-190-4052-5048",
                email: "lizhengyebob@gmail.com",
                contactType: "customer service",
                availableLanguage: "Chinese",
              },
              sameAs: [],
              serviceType: [
                "GEO 搜索体检",
                "品牌 AI 可见度分析",
                "AI 引用优化",
                "AI 曝光持续运营",
              ],
            }),
          }}
        />

        {/* Structured data — WebSite with SearchAction */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              url: BASE_URL,
              name: "GS GEO",
              description: DESCRIPTION,
              inLanguage: "zh-CN",
            }),
          }}
        />
      </head>
      <body className="min-h-screen bg-[#04080f] text-[#f0ece0] antialiased">
        {children}
      </body>
    </html>
  );
}
